---
- name: Run local scala script to delete topics in Zookeeper.
  shell: java -cp tools/util/target/scala-2.11/Util-assembly-0.1.0-SNAPSHOT.jar org.hpi.esb.util.TopicManagement delete -p "{{ topics_prefix }}"
  args:
    chdir: "{{ repository_root_directory }}"

